/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApproveLeaveRequestDto } from './models/approve-leave-request-dto';
export type { AssignRoleDto } from './models/assign-role-dto';
export type { AttendanceDto } from './models/attendance-dto';
export type { AttendanceStatus } from './models/attendance-status';
export type { ChangePasswordDto } from './models/change-password-dto';
export type { CreateLeaveRequestDto } from './models/create-leave-request-dto';
export type { DepartmentDto } from './models/department-dto';
export type { EmployeeDepartmentHistoryDto } from './models/employee-department-history-dto';
export type { EmployeeDto } from './models/employee-dto';
export type { EventDto } from './models/event-dto';
export type { EventParticipantDto } from './models/event-participant-dto';
export type { EventType } from './models/event-type';
export type { ForgotPasswordDto } from './models/forgot-password-dto';
export type { IFormFile } from './models/i-form-file';
export type { LeaveType } from './models/leave-type';
export type { LoginRequestDto } from './models/login-request-dto';
export type { PayslipDto } from './models/payslip-dto';
export type { PayslipStatus } from './models/payslip-status';
export type { RegistrationRequestDto } from './models/registration-request-dto';
export type { ResetPasswordDto } from './models/reset-password-dto';
export type { ResponseDto } from './models/response-dto';
export type { SalaryConfigDto } from './models/salary-config-dto';
export type { TimekeepingDto } from './models/timekeeping-dto';
export type { UpdateParticipantsByEventDto } from './models/update-participants-by-event-dto';
