/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponseDto } from '../../models/response-dto';

export interface ApiEventParticipantsEventIdEmployeeIdGet$Plain$Params {
  eventId: number;
  employeeId: number;
}

export function apiEventParticipantsEventIdEmployeeIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiEventParticipantsEventIdEmployeeIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiEventParticipantsEventIdEmployeeIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('eventId', params.eventId, {});
    rb.path('employeeId', params.employeeId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponseDto>;
    })
  );
}

apiEventParticipantsEventIdEmployeeIdGet$Plain.PATH = '/api/EventParticipants/{eventId}/{employeeId}';
