/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponseDto } from '../../models/response-dto';
import { UpdateParticipantsByEventDto } from '../../models/update-participants-by-event-dto';

export interface ApiEventParticipantsUpdateParticipantsByEventPut$Plain$Params {
      body: UpdateParticipantsByEventDto
}

export function apiEventParticipantsUpdateParticipantsByEventPut$Plain(http: HttpClient, rootUrl: string, params: ApiEventParticipantsUpdateParticipantsByEventPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiEventParticipantsUpdateParticipantsByEventPut$Plain.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponseDto>;
    })
  );
}

apiEventParticipantsUpdateParticipantsByEventPut$Plain.PATH = '/api/EventParticipants/update-participants-by-event';
