/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ResponseDto } from '../../models/response-dto';

export interface ApiEventsByCreatorEmployeeIdMonthYearGet$Json$Params {
  employeeId: number;
  month: number;
  year: number;
}

export function apiEventsByCreatorEmployeeIdMonthYearGet$Json(http: HttpClient, rootUrl: string, params: ApiEventsByCreatorEmployeeIdMonthYearGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ResponseDto>> {
  const rb = new RequestBuilder(rootUrl, apiEventsByCreatorEmployeeIdMonthYearGet$Json.PATH, 'get');
  if (params) {
    rb.path('employeeId', params.employeeId, {});
    rb.path('month', params.month, {});
    rb.path('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ResponseDto>;
    })
  );
}

apiEventsByCreatorEmployeeIdMonthYearGet$Json.PATH = '/api/Events/by-creator/{employeeId}/{month}/{year}';
