/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttendanceStatus } from '../models/attendance-status';
export interface AttendanceDto {
  checkInTime?: string;
  checkOutTime?: (string | null);
  employeeId?: number;
  id?: number;
  isOvertime?: boolean;
  payslipId?: (number | null);
  status?: AttendanceStatus;
  workDate?: string;
}
