/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeaveType } from '../models/leave-type';
export interface CreateLeaveRequestDto {
  employeeId?: number;
  endDate?: string;
  leaveType?: LeaveType;
  reason?: (string | null);
  startDate?: string;
}
