/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartmentDto {
  description?: (string | null);
  id?: number;
  managerId?: (number | null);
  managerName?: (string | null);
  name?: string;
}
