/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EmployeeDepartmentHistoryDto {
  departmentId?: number;
  departmentName?: (string | null);
  employeeId?: number;
  employeeName?: (string | null);
  endDate?: (string | null);
  id?: number;
  isPrimary?: boolean;
  startDate?: string;
}
