/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventType } from '../models/event-type';
export interface EventDto {
  creatorId?: number;
  creatorName?: (string | null);
  description?: (string | null);
  endTime?: (string | null);
  eventDate?: string;
  eventType?: EventType;
  id?: number;
  participantIds?: Array<number>;
  startTime?: (string | null);
  title?: string;
}
