/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PayslipStatus } from '../models/payslip-status';
export interface PayslipDto {
  allowances?: number;
  baseSalary?: number;
  deductions?: number;
  employeeId?: number;
  id?: number;
  month?: number;
  payDate?: string;
  payslipStatus?: PayslipStatus;
  totalPaid?: number;
  year?: number;
}
