/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IFormFile } from '../models/i-form-file';
export interface RegistrationRequestDto {
  email?: string;
  file?: (null | IFormFile | null);
  fullName?: string;
  password?: string;
  phoneNumber?: (string | null);
}
