/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SalaryConfigDto {
  allowances?: number;
  bankAccount?: (string | null);
  bankName?: (string | null);
  baseSalary?: number;
  employeeId?: number;
  id?: number;
  taxCode?: (string | null);
}
